name: reqwest
description: A Dart implementation of rust's reqwest package
version: 0.0.1
repository: https://github.com/mcmah309/reqwest

environment:
  sdk: ^3.5.0

dependencies:
  rust: ^3.1.0
  dio: ^5.7.0
  meta: ^1.0.0
  mime: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
